function cZ4 = Z4_SuspendedLoadxyDst(obj,in2,in3,in4,in5)
%Z4_SuspendedLoadxyDst
%    cZ4 = Z4_SuspendedLoadxyDst(OBJ,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/03/15 01:53:20

Xd4 = in3(:,4);
dXd4 = in3(:,8);
o1 = in2(5,:);
o2 = in2(6,:);
o3 = in2(7,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q3.*2.0;
t7 = q1.*q2.*2.0;
t8 = -t4;
t9 = -t5;
t10 = t6+t7;
t11 = t10.^2;
t12 = t2+t3+t8+t9;
t13 = t12.^2;
t14 = 1.0./t12;
t15 = 1.0./t13;
t16 = t11+t13;
t17 = 1.0./t16;
cZ4 = [-Xd4+atan2(q0.*q3.*2.0+q1.*q2.*2.0,t12);-dXd4+t13.*t17.*(q0.*t14.*2.0+q3.*t10.*t15.*2.0).*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0)+t13.*t17.*(q1.*t14.*2.0+q2.*t10.*t15.*2.0).*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0)+t13.*t17.*(q2.*t14.*2.0-q1.*t10.*t15.*2.0).*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0)-t13.*t17.*(q3.*t14.*2.0-q0.*t10.*t15.*2.0).*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0)];
end
