function [A_load,b_load] = CBF_Constraints_Load(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Load
%    [A_load,B_LOAD] = CBF_Constraints_Load(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026/06/06 01:45:48

A_load = zeros(0,0);
if nargout > 1
    b_load = zeros(0,0);
end
end
