function [A_drone,b_drone] = CBF_Constraints_Drone(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Drone
%    [A_drone,B_DRONE] = CBF_Constraints_Drone(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026/06/06 01:45:49

A_drone = zeros(0,0);
if nargout > 1
    b_drone = zeros(0,0);
end
end
