function dxf = FL_CBF(in1,in2)
%FL_CBF
%    DXF = FL_CBF(IN1,IN2)
% Input order:
% in1 (state) = ["pl1", "pl2", "pl3", "dpl1", "dpl2", "dpl3", "pT1", "pT2", "pT3", "ol1", "ol2", "ol3"];
% in2 (parameter) = ["m", "Lx", "Ly", "lx", "ly", "jx", "jy", "jz", "gravity", "km1", "km2", "km3", "km4", "k1", "k2", "k3", "k4", "rotor_r", "mL", "cableL"];



%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/02 20:28:59

cableL = in2(:,20);
dpl1 = in1(4,:);
dpl2 = in1(5,:);
dpl3 = in1(6,:);
gravity = in2(:,9);
m = in2(:,1);
mL = in2(:,19);
ol1 = in1(10,:);
ol2 = in1(11,:);
ol3 = in1(12,:);
pT1 = in1(7,:);
pT2 = in1(8,:);
pT3 = in1(9,:);
t2 = m+mL;
t3 = ol1.*pT2;
t4 = ol2.*pT1;
t5 = ol1.*pT3;
t6 = ol3.*pT1;
t7 = ol2.*pT3;
t8 = ol3.*pT2;
t9 = -t4;
t10 = -t6;
t11 = -t8;
t12 = 1.0./t2;
t13 = t3+t9;
t14 = t5+t10;
t15 = t7+t11;
t16 = t13.^2;
t17 = t14.^2;
t18 = t15.^2;
t19 = t16+t17+t18;
dxf = [dpl1;dpl2;dpl3;-cableL.*m.*pT1.*t12.*t19;-cableL.*m.*pT2.*t12.*t19;-gravity-cableL.*m.*pT3.*t12.*t19;t15;-t5+t6;t13;0.0;0.0;0.0];
end
