function dxg = GLxyDst_CBF(in1,in2)
%GLxyDst_CBF
%    DXG = GLxyDst_CBF(IN1,IN2)
% Input order:
% in1 (state) = ["pl1", "pl2", "pl3", "dpl1", "dpl2", "dpl3", "pT1", "pT2", "pT3", "ol1", "ol2", "ol3"];
% in2 (parameter) = ["m", "Lx", "Ly", "lx", "ly", "jx", "jy", "jz", "gravity", "km1", "km2", "km3", "km4", "k1", "k2", "k3", "k4", "rotor_r", "mL", "cableL", "dstx", "dsty"];



%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/02 20:28:59

cableL = in2(:,20);
m = in2(:,1);
mL = in2(:,19);
pT1 = in1(7,:);
pT2 = in1(8,:);
pT3 = in1(9,:);
t2 = m+mL;
t3 = 1.0./cableL;
t4 = 1.0./m;
t5 = 1.0./t2;
t9 = pT1.*t3.*t4;
t10 = pT2.*t3.*t4;
t11 = pT3.*t3.*t4;
t6 = pT1.*pT2.*t5;
t7 = pT1.*pT3.*t5;
t8 = pT2.*pT3.*t5;
dxg = reshape([0.0,0.0,0.0,pT1.^2.*t5,t6,t7,0.0,0.0,0.0,0.0,-t11,t10,0.0,0.0,0.0,t6,pT2.^2.*t5,t8,0.0,0.0,0.0,t11,0.0,-t9,0.0,0.0,0.0,t7,t8,pT3.^2.*t5,0.0,0.0,0.0,-t10,t9,0.0],[12,3]);
end
