%% Publication-style trajectory comparison figures
clear; close all hidden; clc;

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(fileparts(script_dir)));
addpath(genpath(repo_root));
cd(script_dir);

%% User settings
cases = struct( ...
    'name', { ...
        'Lemniscate', ...
        'Heart', ...
        'Square', ...
        'Star', ...
        'Circle'}, ...
    'files', { ...
        {'figure8noerr52s_Log(05-Apr-2026_18_23_01).mat', ...
         'figure8err52s_Log(05-Apr-2026_18_25_40).mat', ...
         'figure8errcom52smode5_Log(06-Apr-2026_15_17_59).mat'}, ...
        {'heartnoerr36s_Log(05-Apr-2026_15_08_57).mat', ...
         'hearterr36s_Log(05-Apr-2026_15_10_12).mat', ...
         'hearterrcom36smode5_Log(06-Apr-2026_15_15_45).mat'}, ...
        {'square36noerr_Log(05-Apr-2026_17_39_25).mat', ...
         'square36err_Log(05-Apr-2026_17_40_58).mat', ...
         'square36errcommode5_Log(05-Apr-2026_17_42_02).mat'}, ...
        {'starnoerr48_Log(05-Apr-2026_17_16_48).mat', ...
         'starerr48_Log(05-Apr-2026_17_15_22).mat', ...
         'starerrcom48smode5_Log(06-Apr-2026_15_19_36).mat'}, ...
        {'circlenoerr52s_Log(06-Apr-2026_17_37_10).mat', ...
         'circleerr52s_Log(06-Apr-2026_17_35_48).mat', ...
         'circleerrcom52smode5_Log(06-Apr-2026_17_34_20).mat'} ...
    });
% cases = struct( ...
%     'name', { ...
%         'Spline', ...
%         'PointtoPoint', ...
%         'Saddle', ...
%         'Lemniscate', ...
%         'Heart', ...
%         'Star'}, ...
%     'files', { ...
%         {'HL_nominal_12_Log(12-Jun-2026_14_36_46).mat', ...
%          'HL_degraded_12_Log(12-Jun-2026_11_27_08).mat', ...
%          'HL_compensated_12_Log(12-Jun-2026_12_56_42).mat'}, ...
%         {'HL_nominal_43_Log(12-Jun-2026_14_45_16).mat', ...
%          'HL_degraded_43_Log(12-Jun-2026_11_35_25).mat', ...
%          'HL_compensated_43_Log(12-Jun-2026_13_05_32).mat'}, ...
%         {'HL_nominal_60_Log(12-Jun-2026_14_49_54).mat', ...
%          'HL_degraded_60_Log(12-Jun-2026_11_39_54).mat', ...
%          'HL_compensated_60_Log(12-Jun-2026_13_10_24).mat'}, ...
%         {'HL_nominal_101_Log(12-Jun-2026_15_01_20).mat', ...
%          'HL_degraded_101_Log(12-Jun-2026_11_50_48).mat', ...
%          'HL_compensated_101_Log(12-Jun-2026_13_21_57).mat'}, ...
%         {'HL_nominal_107_Log(12-Jun-2026_15_03_01).mat', ...
%          'HL_degraded_107_Log(12-Jun-2026_11_52_24).mat', ...
%          'HL_compensated_107_Log(12-Jun-2026_13_23_39).mat'}, ...
%         {'HL_nominal_113_Log(12-Jun-2026_15_04_43).mat', ...
%          'HL_degraded_113_Log(12-Jun-2026_11_54_00).mat', ...
%          'HL_compensated_113_Log(12-Jun-2026_13_25_22).mat'} ...
%     });
run_labels = {'LPV-MPC', 'LPV-MPC + Model Error', 'LPV-MPC + EDMD-MEC'};
run_styles = {'-', '-', '-'};
run_colors = [
    0.10, 0.35, 0.90;
    0.86, 0.24, 0.12;
    0.00, 0.62, 0.32
];

font_name = 'Times New Roman';
font_size = 13;
line_width = 1.2;
ref_line_width = 3.0;
flight_phase_only = true;
run_markers = {'o', 's', '^'};
marker_spacing_each = [45, 45, 20];
marker_spacing_inset = [10, 10, 5];

output_dir = fullfile(script_dir, 'trajectory_figures');
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

%% Figures
for case_idx = 1:numel(cases)
    run_files = cases(case_idx).files;
    n_runs = numel(run_files);
    runs = cell(1, n_runs);
    for i = 1:n_runs
        runs{i} = load_run(run_files{i}, run_labels{i});
    end

    time_range = intersect_time_range(runs);
    phase_option = [];
    if flight_phase_only
        phase_option = 'f';
    end

    fig = figure(199 + case_idx); clf(fig);
    fig.Color = 'w';
    fig.Position(3:4) = [980, 760];
    ax = axes(fig);
    hold(ax, 'on');

    ref_phase = get_series(runs{1}.logger, "p", "r", time_range, phase_option);
    h_ref = plot3(ax, ref_phase(:, 1), ref_phase(:, 2), ref_phase(:, 3), ...
        'Color', [0.35, 0.35, 0.35], ...
        'LineStyle', '--', ...
        'LineWidth', 2.0, ...
        'DisplayName', 'Reference');

    plot_order = [2, 3, 1];
    h_runs = gobjects(1, n_runs);
    for idx = plot_order
        p_phase = get_series(runs{idx}.logger, "p", "e", time_range, phase_option);
        h_runs(idx) = plot3(ax, p_phase(:, 1), p_phase(:, 2), p_phase(:, 3), ...
            'Color', run_colors(idx, :), ...
            'LineStyle', run_styles{idx}, ...
            'LineWidth', line_width + (idx == 1) * 0.4, ...
            'Marker', run_markers{idx}, ...
            'MarkerIndices', 1:marker_spacing_each(idx):size(p_phase, 1), ...
            'MarkerSize', 4.5, ...
            'MarkerFaceColor', 'none', ...
            'DisplayName', run_labels{idx});
        plot3(ax, p_phase(1, 1), p_phase(1, 2), p_phase(1, 3), ...
            'o', ...
            'MarkerSize', 6.5, ...
            'MarkerFaceColor', run_colors(idx, :), ...
            'MarkerEdgeColor', run_colors(idx, :), ...
            'HandleVisibility', 'off');
    end

    grid(ax, 'on');
    box(ax, 'on');
    axis(ax, 'equal');
    view(ax, [-38, 24]);
    xlabel(ax, 'x [m]', 'FontName', font_name, 'FontSize', font_size);
    ylabel(ax, 'y [m]', 'FontName', font_name, 'FontSize', font_size);
    zlabel(ax, 'z [m]', 'FontName', font_name, 'FontSize', font_size);
    title(ax, sprintf('%s Trajectory Tracking Performance', cases(case_idx).name), ...
        'FontName', font_name, 'FontSize', font_size + 3);
    set(ax, 'FontName', font_name, 'FontSize', font_size, 'LineWidth', 1.0);
    legend(ax, [h_ref, h_runs], [{'Reference'}, run_labels], ...
        'Location', 'northeastoutside', 'FontName', font_name, 'FontSize', font_size - 1);

    safe_name = lower(regexprep(cases(case_idx).name, '[^a-zA-Z0-9]+', '_'));
    exportgraphics(fig, fullfile(output_dir, sprintf('%s_trajectory.png', safe_name)), 'Resolution', 300);
end

%% Local functions
function run = load_run(file_name, label)
    DATA_DIR = 'C:\Users\student\Documents\GitHub\common_matlab\Data\Sim_data';
    full_path = fullfile(DATA_DIR, file_name);
    if ~isfile(full_path)
        error('File not found: %s', full_path);
    end
    run = struct();
    run.label = label;
    run.logger = LOGGER(full_path);
end

function time_range = intersect_time_range(runs)
    t_starts = zeros(1, numel(runs));
    t_ends = zeros(1, numel(runs));
    for idx = 1:numel(runs)
        t = runs{idx}.logger.Data.t;
        t_starts(idx) = min(t);
        t_ends(idx) = max(t);
    end
    time_range = [max(t_starts), min(t_ends)];
end

function data = get_series(logger_obj, variable, attribute, time_range, phase_option)
    if nargin < 5 || isempty(phase_option)
        raw = logger_obj.data(1, variable, attribute, "ranget", time_range);
    else
        raw = logger_obj.data(1, variable, attribute, "ranget", time_range, "phase", phase_option);
    end
    data = normalize_series(raw);
end

function data = normalize_series(raw)
    data = double(squeeze(raw));
    if isvector(data)
        data = data(:);
    end
    if size(data, 1) < size(data, 2)
        data = data.';
    end
end
