function [violation,v_correct_dir,h_0] = Analytical_ROM_CBF_Velocity(in1,in2,in3,R_safe,alpha_gain)
%Analytical_ROM_CBF_Velocity
%    [VIOLATION,V_CORRECT_DIR,H_0] = Analytical_ROM_CBF_Velocity(IN1,IN2,IN3,R_safe,ALPHA_GAIN)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/12 02:25:05

p_obs1 = in3(1,:);
p_obs2 = in3(2,:);
p_obs3 = in3(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v_nom1 = in2(1,:);
v_nom2 = in2(2,:);
v_nom3 = in2(3,:);
t2 = R_safe.^2;
t3 = p_obs1.*2.0;
t4 = p_obs2.*2.0;
t5 = p_obs3.*2.0;
t6 = q1.*2.0;
t7 = q2.*2.0;
t8 = q3.*2.0;
t9 = -q1;
t11 = -q2;
t13 = -q3;
t10 = -t6;
t12 = -t7;
t14 = -t8;
t15 = -t2;
t16 = p_obs1+t9;
t17 = p_obs2+t11;
t18 = p_obs3+t13;
t19 = t3+t10;
t20 = t4+t12;
t21 = t5+t14;
t22 = t16.^2;
t23 = t17.^2;
t24 = t18.^2;
t25 = t19.^2;
t26 = t20.^2;
t27 = t21.^2;
t28 = t15+t22+t23+t24;
violation = -alpha_gain.*t28+t19.*v_nom1+t20.*v_nom2+t21.*v_nom3;
if nargout > 1
    t29 = t25+t26+t27+1.0e-6;
    t30 = 1.0./t29;
    v_correct_dir = [-t19.*t30;-t20.*t30;-t21.*t30];
end
if nargout > 2
    h_0 = t28;
end
end
