function [A_att,b_att,h_att] = Attitude_Limit_CBF(in1,in2,cos_gamma_max,in4)
%Attitude_Limit_CBF
%    [A_att,B_ATT,H_ATT] = Attitude_Limit_CBF(IN1,IN2,COS_GAMMA_MAX,IN4)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/05 17:57:11

jx = in2(1,:);
jy = in2(2,:);
jz = in2(3,:);
k0 = in4(1,:);
k1 = in4(2,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
w1 = in1(5,:);
w2 = in1(6,:);
w3 = in1(7,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q0.*q1.*2.0;
t7 = q0.*q2.*2.0;
t8 = q1.*q3.*2.0;
t9 = q2.*q3.*2.0;
t10 = 1.0./jx;
t11 = 1.0./jy;
t13 = (q0.*w1)./2.0;
t14 = (q0.*w2)./2.0;
t15 = (q1.*w1)./2.0;
t16 = (q0.*w3)./2.0;
t17 = (q1.*w2)./2.0;
t18 = (q2.*w1)./2.0;
t19 = (q1.*w3)./2.0;
t20 = (q2.*w2)./2.0;
t21 = (q3.*w1)./2.0;
t22 = (q2.*w3)./2.0;
t23 = (q3.*w2)./2.0;
t24 = (q3.*w3)./2.0;
t12 = -t8;
t25 = -t18;
t26 = -t19;
t27 = -t23;
t28 = t6+t9;
t30 = t15+t20+t24;
t29 = t7+t12;
A_att = [0.0,t10.*t28,t11.*t29,0.0];
if nargout > 1
    t31 = t16+t17+t25;
    t32 = t14+t21+t26;
    t33 = t13+t22+t27;
    b_att = -k0.*(cos_gamma_max-t2+t3+t4-t5)-k1.*(q0.*t30.*2.0+q1.*t33.*2.0+q2.*t32.*2.0-q3.*t31.*2.0)+t30.*(q1.*w1.*2.0+q2.*w2.*2.0)+t31.*(q1.*w2.*2.0-q2.*w1.*2.0)-t32.*(q0.*w2.*2.0+q3.*w1.*2.0)-t33.*(q0.*w1.*2.0-q3.*w2.*2.0)+t11.*t29.*(jx.*w1.*w3-jz.*w1.*w3)-t10.*t28.*(jy.*w2.*w3-jz.*w2.*w3);
end
if nargout > 2
    h_att = -cos_gamma_max+t2-t3-t4+t5;
end
end
