function [A_qp_cb,b_qp_cb] = CBF_cable_angle(obj,in2,theta_max_deg,in4,in5)
%CBF_cable_angle
%    [A_qp_cb,B_QP_CB] = CBF_cable_angle(OBJ,IN2,THETA_MAX_DEG,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/02 21:51:03

cableL = in5(:,7);
gamma_c1 = in4(1,:);
gamma_c2 = in4(2,:);
m = in5(:,1);
ol1 = in2(10,:);
ol2 = in2(11,:);
ol3 = in2(12,:);
pT1 = in2(7,:);
pT2 = in2(8,:);
pT3 = in2(9,:);
t2 = ol1.*pT2;
t3 = ol2.*pT1;
t4 = 1.0./cableL;
t5 = 1.0./m;
A_qp_cb = [pT1.*pT3.*t4.*t5,pT2.*pT3.*t4.*t5,-pT1.^2.*t4.*t5-pT2.^2.*t4.*t5];
if nargout > 1
    t6 = -t3;
    b_qp_cb = -gamma_c1.*(t2+t6)-gamma_c2.*(t2+t6+gamma_c1.*(pT3+cos((theta_max_deg.*pi)./1.8e+2)))+ol1.*(ol1.*pT3-ol3.*pT1)+ol2.*(ol2.*pT3-ol3.*pT2);
end
end
