function [A_drone,b_drone] = CBF_Constraints_Drone(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Drone
%    [A_drone,B_DRONE] = CBF_Constraints_Drone(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/06 16:36:00

cableL = in5(14,:);
d1 = in5(6,:);
d2 = in5(7,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in5(1,:);
oy = in5(2,:);
oz = in5(3,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
r_drone = in5(5,:);
ro = in5(4,:);
A_drone = [-ox+pl1+cableL.*pT1,-oy+pl2+cableL.*pT2,-oz+pl3+cableL.*pT3];
if nargout > 1
    b_drone = -(dpl3+cableL.*ol1.*pT2-cableL.*ol2.*pT1).^2-(dpl2-cableL.*ol1.*pT3+cableL.*ol3.*pT1).^2-(dpl1+cableL.*ol2.*pT3-cableL.*ol3.*pT2).^2-d2.*((dpl1+cableL.*ol2.*pT3-cableL.*ol3.*pT2).*(-ox+pl1+cableL.*pT1)+(dpl2-cableL.*ol1.*pT3+cableL.*ol3.*pT1).*(-oy+pl2+cableL.*pT2)+(dpl3+cableL.*ol1.*pT2-cableL.*ol2.*pT1).*(-oz+pl3+cableL.*pT3)+d1.*(abs(-ox+pl1+cableL.*pT1).^2./2.0+abs(-oy+pl2+cableL.*pT2).^2./2.0+abs(-oz+pl3+cableL.*pT3).^2./2.0-(r_drone+ro).^2./2.0));
end
end
