function [A_drone,b_drone] = CBF_Constraints_Drone(obj,in2,in3,in4,t)
%CBF_Constraints_Drone
%    [A_drone,B_DRONE] = CBF_Constraints_Drone(OBJ,IN2,IN3,IN4,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/22 20:20:08

cableL_hlc = in4(14,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
k_drone1 = in4(6,:);
k_drone2 = in4(7,:);
loadmass_hlc = in4(13,:);
mass_hlc = in4(8,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in4(1,:);
oy = in4(2,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
r_drone = in4(5,:);
ro = in4(4,:);
t2 = cableL_hlc.*pT1;
t3 = cableL_hlc.*pT2;
t4 = loadmass_hlc+mass_hlc;
t5 = cableL_hlc.^2;
t6 = dpl1.^2;
t7 = dpl2.^2;
t8 = ol1.^2;
t9 = ol2.^2;
t10 = ol3.^2;
t11 = pT1.^2;
t13 = pT2.^2;
t16 = pT3.^2;
t18 = q0.^2;
t19 = q1.^2;
t20 = q2.^2;
t21 = q3.^2;
t22 = q0.*q1.*2.0;
t23 = q0.*q2.*2.0;
t24 = q1.*q3.*2.0;
t25 = q2.*q3.*2.0;
t26 = 1.0./mass_hlc;
t27 = -ox;
t28 = -oy;
t29 = 1.0./pT3;
t41 = pT2.*q0.*q1.*-2.0;
t30 = -t25;
t31 = pT3.*t18;
t32 = pT3.*t19;
t33 = pT3.*t20;
t34 = pT3.*t21;
t35 = pT1.*t23;
t37 = pT1.*t24;
t38 = pT2.*t25;
t39 = -t19;
t40 = -t20;
t44 = pl1+t2+t27;
t45 = pl2+t3+t28;
t46 = t23+t24;
t42 = -t32;
t43 = -t33;
t47 = t22+t30;
t48 = t18+t21+t39+t40;
t49 = t31+t34+t35+t37+t38+t41+t42+t43;
t50 = 1.0./t49;
A_drone = [pT1.*t29.*t44+pT2.*t29.*t45+t4.*t26.*t44.*t50.*(pT1.*t48-pT3.*t46)+t4.*t26.*t45.*t50.*(pT2.*t48+pT3.*t47)+(t4.*t26.*t29.*t50.*(pT1.*t47+pT2.*t46).*(t2.*t45-t3.*t44))./cableL_hlc,0.0,0.0,0.0];
if nargout > 1
    et1 = loadmass_hlc.*t6+loadmass_hlc.*t7+mass_hlc.*t6+mass_hlc.*t7-loadmass_hlc.*t2.^2.*t9-loadmass_hlc.*t3.^2.*t8-mass_hlc.*t2.^2.*t9-mass_hlc.*t3.^2.*t8+dpl1.*k_drone1.*loadmass_hlc.*pl1+dpl2.*k_drone1.*loadmass_hlc.*pl2+dpl1.*k_drone1.*mass_hlc.*pl1+dpl2.*k_drone1.*mass_hlc.*pl2+dpl1.*k_drone1.*loadmass_hlc.*t2+dpl2.*k_drone1.*loadmass_hlc.*t3+dpl1.*k_drone1.*loadmass_hlc.*t27+dpl2.*k_drone1.*loadmass_hlc.*t28+dpl1.*k_drone1.*mass_hlc.*t2+dpl2.*k_drone1.*mass_hlc.*t3+dpl1.*k_drone1.*mass_hlc.*t27+dpl2.*k_drone1.*mass_hlc.*t28-dpl1.*loadmass_hlc.*ol3.*t3.*2.0+dpl2.*loadmass_hlc.*ol3.*t2.*2.0-dpl1.*mass_hlc.*ol3.*t3.*2.0+dpl2.*mass_hlc.*ol3.*t2.*2.0+loadmass_hlc.*ox.*t2.*t9+loadmass_hlc.*ox.*t2.*t10+loadmass_hlc.*oy.*t3.*t8+loadmass_hlc.*oy.*t3.*t10+mass_hlc.*ox.*t2.*t9+mass_hlc.*ox.*t2.*t10+mass_hlc.*oy.*t3.*t8+mass_hlc.*oy.*t3.*t10-loadmass_hlc.*pl1.*t2.*t9-loadmass_hlc.*pl1.*t2.*t10-loadmass_hlc.*pl2.*t3.*t8-loadmass_hlc.*pl2.*t3.*t10;
    et2 = -mass_hlc.*pl1.*t2.*t9-mass_hlc.*pl1.*t2.*t10-mass_hlc.*pl2.*t3.*t8-mass_hlc.*pl2.*t3.*t10+loadmass_hlc.*t5.*t8.*t16+loadmass_hlc.*t5.*t9.*t16+mass_hlc.*t5.*t8.*t16+mass_hlc.*t5.*t9.*t16-mass_hlc.*t2.^2.*t9.*t11-mass_hlc.*t2.^2.*t8.*t13-mass_hlc.*t2.^2.*t10.*t11-mass_hlc.*t2.^2.*t9.*t13-mass_hlc.*t3.^2.*t8.*t13-mass_hlc.*t2.^2.*t10.*t13.*2.0-mass_hlc.*t2.^2.*t8.*t16-mass_hlc.*t3.^2.*t10.*t13-mass_hlc.*t2.^2.*t9.*t16-mass_hlc.*t3.^2.*t8.*t16-mass_hlc.*t3.^2.*t9.*t16+cableL_hlc.*dpl1.*loadmass_hlc.*ol2.*pT3.*2.0-cableL_hlc.*dpl2.*loadmass_hlc.*ol1.*pT3.*2.0+cableL_hlc.*dpl1.*mass_hlc.*ol2.*pT3.*2.0-cableL_hlc.*dpl2.*mass_hlc.*ol1.*pT3.*2.0+k_drone1.*loadmass_hlc.*ol3.*ox.*t3+k_drone1.*mass_hlc.*ol3.*ox.*t3-k_drone1.*loadmass_hlc.*ol3.*pl1.*t3;
    et3 = k_drone1.*loadmass_hlc.*ol3.*pl2.*t2-k_drone1.*mass_hlc.*ol3.*pl1.*t3+k_drone1.*mass_hlc.*ol3.*pl2.*t2+k_drone1.*loadmass_hlc.*ol3.*t2.*t28+loadmass_hlc.*ol1.*ol2.*pl1.*t3+loadmass_hlc.*ol1.*ol2.*pl2.*t2+k_drone1.*mass_hlc.*ol3.*t2.*t28+mass_hlc.*ol1.*ol2.*pl1.*t3+mass_hlc.*ol1.*ol2.*pl2.*t2+loadmass_hlc.*ol1.*ol2.*t2.*t3.*2.0+loadmass_hlc.*ol1.*ol2.*t2.*t28+loadmass_hlc.*ol1.*ol2.*t3.*t27+mass_hlc.*ol1.*ol2.*t2.*t3.*2.0+mass_hlc.*ol1.*ol2.*t2.*t28+mass_hlc.*ol1.*ol2.*t3.*t27+mass_hlc.*ox.*t2.*t9.*t11+mass_hlc.*ox.*t2.*t8.*t13+mass_hlc.*ox.*t2.*t10.*t11+mass_hlc.*ox.*t2.*t10.*t13+mass_hlc.*ox.*t2.*t8.*t16+mass_hlc.*ox.*t2.*t9.*t16+mass_hlc.*oy.*t3.*t8.*t13+mass_hlc.*oy.*t3.*t10.*t13+mass_hlc.*oy.*t3.*t8.*t16+mass_hlc.*oy.*t3.*t9.*t16-mass_hlc.*pl1.*t2.*t9.*t11-mass_hlc.*pl1.*t2.*t8.*t13-mass_hlc.*pl1.*t2.*t10.*t11-mass_hlc.*pl1.*t2.*t10.*t13-mass_hlc.*pl2.*t3.*t8.*t13;
    et4 = -mass_hlc.*pl1.*t2.*t8.*t16-mass_hlc.*pl1.*t2.*t9.*t16-mass_hlc.*pl2.*t3.*t10.*t13-mass_hlc.*pl2.*t3.*t8.*t16-mass_hlc.*pl2.*t3.*t9.*t16-mass_hlc.*ol1.*ol2.*oy.*t2.*t13.*2.0+mass_hlc.*ol1.*ol2.*pl2.*t2.*t13.*2.0+mass_hlc.*oy.*pT1.*pT2.*t2.*t9+mass_hlc.*oy.*pT1.*pT2.*t2.*t10-mass_hlc.*pT1.*pT2.*pl2.*t2.*t9-mass_hlc.*pT1.*pT2.*pl2.*t2.*t10+mass_hlc.*ol1.*ol2.*t2.*t3.*t13.*2.0+mass_hlc.*ol1.*ol2.*pT1.*pT2.*t2.^2.*2.0+mass_hlc.*ol1.*ol3.*pT1.*pT3.*t2.^2.*2.0+mass_hlc.*ol2.*ol3.*pT2.*pT3.*t2.^2.*2.0+mass_hlc.*ol2.*ol3.*pT2.*pT3.*t3.^2.*2.0+cableL_hlc.*k_drone1.*loadmass_hlc.*ol1.*oy.*pT3+cableL_hlc.*k_drone1.*mass_hlc.*ol1.*oy.*pT3-cableL_hlc.*k_drone1.*loadmass_hlc.*ol1.*pT3.*pl2+cableL_hlc.*k_drone1.*loadmass_hlc.*ol2.*pT3.*pl1-cableL_hlc.*k_drone1.*mass_hlc.*ol1.*pT3.*pl2+cableL_hlc.*k_drone1.*mass_hlc.*ol2.*pT3.*pl1-cableL_hlc.*k_drone1.*loadmass_hlc.*ol1.*pT3.*t3+cableL_hlc.*k_drone1.*loadmass_hlc.*ol2.*pT3.*t2;
    et5 = cableL_hlc.*k_drone1.*loadmass_hlc.*ol2.*pT3.*t27+cableL_hlc.*loadmass_hlc.*ol1.*ol3.*pT3.*pl1+cableL_hlc.*loadmass_hlc.*ol2.*ol3.*pT3.*pl2-cableL_hlc.*k_drone1.*mass_hlc.*ol1.*pT3.*t3+cableL_hlc.*k_drone1.*mass_hlc.*ol2.*pT3.*t2+cableL_hlc.*k_drone1.*mass_hlc.*ol2.*pT3.*t27+cableL_hlc.*mass_hlc.*ol1.*ol3.*pT3.*pl1+cableL_hlc.*mass_hlc.*ol2.*ol3.*pT3.*pl2-cableL_hlc.*loadmass_hlc.*ol1.*ol3.*pT3.*t2-cableL_hlc.*loadmass_hlc.*ol2.*ol3.*pT3.*t3+cableL_hlc.*loadmass_hlc.*ol1.*ol3.*pT3.*t27+cableL_hlc.*loadmass_hlc.*ol2.*ol3.*pT3.*t28-cableL_hlc.*mass_hlc.*ol1.*ol3.*pT3.*t2-cableL_hlc.*mass_hlc.*ol2.*ol3.*pT3.*t3+cableL_hlc.*mass_hlc.*ol1.*ol3.*pT3.*t27+cableL_hlc.*mass_hlc.*ol2.*ol3.*pT3.*t28-mass_hlc.*ol1.*ol2.*ox.*pT1.*pT2.*t2.*2.0-mass_hlc.*ol1.*ol3.*ox.*pT1.*pT3.*t2.*2.0-mass_hlc.*ol2.*ol3.*ox.*pT2.*pT3.*t2.*2.0-mass_hlc.*ol1.*ol3.*oy.*pT2.*pT3.*t2.*2.0-mass_hlc.*ol2.*ol3.*oy.*pT2.*pT3.*t3.*2.0+mass_hlc.*ol1.*ol2.*pT1.*pT2.*pl1.*t2.*2.0+mass_hlc.*ol1.*ol3.*pT1.*pT3.*pl1.*t2.*2.0+mass_hlc.*ol1.*ol3.*pT2.*pT3.*pl2.*t2.*2.0;
    et6 = mass_hlc.*ol2.*ol3.*pT2.*pT3.*pl1.*t2.*2.0+mass_hlc.*ol2.*ol3.*pT2.*pT3.*pl2.*t3.*2.0+mass_hlc.*ol1.*ol3.*pT2.*pT3.*t2.*t3.*2.0;
    b_drone = k_drone2.*(dpl1.*t44+dpl2.*t45+k_drone1.*((r_drone+ro).^2.*(-1.0./2.0)+t44.^2./2.0+t45.^2./2.0)-cableL_hlc.*t45.*(ol1.*pT3-ol3.*pT1)+cableL_hlc.*t44.*(ol2.*pT3-ol3.*pT2))+(et1+et2+et3+et4+et5+et6)./t4;
end
end
