function [A_qp,b_qp] = CBF_Constraints_z(obj,in2,in3,in4,in5,in6,rl,in8)
%CBF_Constraints_z
%    [A_qp,B_QP] = CBF_Constraints_z(OBJ,IN2,IN3,IN4,IN5,IN6,RL,IN8)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/07/29 15:48:09

cableL = in8(:,7);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
dstx = in8(:,8);
dsty = in8(:,9);
gamma1 = in6(1,:);
gamma2 = in6(2,:);
gravity = in8(:,5);
m = in8(:,1);
mL = in8(:,6);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
ro = in5(4,:);
xo = in5(1,:);
yo = in5(2,:);
zo = in5(3,:);
t2 = m+mL;
t3 = ol1.*pT2;
t4 = ol2.*pT1;
t5 = ol1.*pT3;
t6 = ol3.*pT1;
t7 = ol2.*pT3;
t8 = ol3.*pT2;
t9 = pl1.*2.0;
t10 = pl2.*2.0;
t11 = pl3.*2.0;
t12 = q0.^2;
t13 = q1.^2;
t14 = q2.^2;
t15 = q3.^2;
t16 = xo.*2.0;
t17 = yo.*2.0;
t18 = zo.*2.0;
t29 = pT1.*q0.*q2.*2.0;
t30 = pT2.*q0.*q1.*2.0;
t31 = pT1.*q1.*q3.*2.0;
t32 = pT2.*q2.*q3.*2.0;
t19 = -t16;
t20 = -t17;
t21 = -t18;
t22 = -t4;
t23 = -t6;
t24 = -t8;
t25 = pT3.*t12;
t26 = pT3.*t13;
t27 = pT3.*t14;
t28 = pT3.*t15;
t33 = 1.0./t2;
t34 = -t30;
t35 = -t26;
t36 = -t27;
t37 = t9+t19;
t38 = t10+t20;
t39 = t11+t21;
t40 = t3+t22;
t41 = t5+t23;
t42 = t7+t24;
t43 = t40.^2;
t44 = t41.^2;
t45 = t42.^2;
t47 = t25+t28+t29+t31+t32+t34+t35+t36;
A_qp = -pT1.*t33.*t37.*t47-pT2.*t33.*t38.*t47-pT3.*t33.*t39.*t47;
if nargout > 1
    t46 = t43+t44+t45;
    b_qp = gamma2.*(dpl1.*t37+dpl2.*t38+dpl3.*t39+gamma1.*((pl1-xo).^2+(pl2-yo).^2+(pl3-zo).^2-(rl+ro).^2))+t37.*(dstx-cableL.*m.*pT1.*t33.*t46)+t38.*(dsty-cableL.*m.*pT2.*t33.*t46)+dpl1.*(dpl1.*2.0+gamma1.*t37)+dpl2.*(dpl2.*2.0+gamma1.*t38)+dpl3.*(dpl3.*2.0+gamma1.*t39)-t39.*(gravity+cableL.*m.*pT3.*t33.*t46);
end
end
