function [A_drone_top,b_drone_top] = CBF_Constraints_Drone(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Drone
%    [A_drone_top,B_DRONE_TOP] = CBF_Constraints_Drone(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/08 14:05:16

cableL = in5(14,:);
d1 = in5(6,:);
d2 = in5(7,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in5(1,:);
oy = in5(2,:);
oz = in5(3,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
r_drone = in5(5,:);
ro = in5(4,:);
A_drone_top = [0.0,0.0,0.0];
if nargout > 1
    t2 = cableL.*pT1;
    t3 = cableL.*pT2;
    t4 = cableL.*pT3;
    t5 = -ox;
    t6 = -oy;
    t7 = -oz;
    t8 = pl1+t2+t5;
    t9 = pl2+t3+t6;
    t10 = pl3+t4+t7;
    b_drone_top = d2.*(t8.*(dpl1+cableL.*(ol2.*pT3-ol3.*pT2))+t10.*(dpl3+cableL.*(ol1.*pT2-ol2.*pT1))+t9.*(dpl2-cableL.*(ol1.*pT3-ol3.*pT1))+d1.*((r_drone+ro).^2.*(-1.0./2.0)+t8.^2./2.0+t9.^2./2.0+t10.^2./2.0));
end
end
