function [A_load_top,b_load_top] = CBF_Constraints_Load_TopLayer(obj,in2,in3,in4,t)
%CBF_Constraints_Load_TopLayer
%    [A_load_top,B_LOAD_TOP] = CBF_Constraints_Load_TopLayer(OBJ,IN2,IN3,IN4,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/09 19:09:34

cableL = in4(17,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
gravity = in4(15,:);
k_cbf1 = in4(6,:);
k_cbf2 = in4(7,:);
m = in4(11,:);
mL = in4(16,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in4(1,:);
oy = in4(2,:);
oz = in4(3,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
r_load = in4(5,:);
ro = in4(4,:);
t2 = m+mL;
t3 = ol1.^2;
t4 = ol2.^2;
t5 = ol3.^2;
t6 = pT1.^2;
t7 = pT2.^2;
t8 = pT3.^2;
t9 = pT3.^3;
t10 = 1.0./pT3;
t11 = -pl1;
t12 = -pl2;
t13 = -pl3;
t18 = cableL.*m.*ol1.*ol2.*pT1.*pT2.*pT3.*2.0;
t14 = 1.0./t2;
t15 = ox+t11;
t16 = oy+t12;
A_load_top = [-oz+pl3-pT1.*t10.*t15-pT2.*t10.*t16,0.0,0.0];
if nargout > 1
    t17 = oz+t13;
    t19 = cableL.*m.*t3.*t9;
    t20 = cableL.*m.*t4.*t9;
    t21 = cableL.*m.*pT3.*t3.*t7;
    t22 = cableL.*m.*pT3.*t4.*t6;
    t23 = cableL.*m.*pT3.*t5.*t6;
    t24 = cableL.*m.*pT3.*t5.*t7;
    t25 = cableL.*m.*ol1.*ol3.*pT1.*t8.*2.0;
    t26 = cableL.*m.*ol2.*ol3.*pT2.*t8.*2.0;
    t27 = -t18;
    t28 = -t25;
    t29 = -t26;
    t30 = t19+t20+t21+t22+t23+t24+t27+t28+t29;
    b_load_top = -k_cbf2.*(dpl1.*t15+dpl2.*t16+dpl3.*t17-k_cbf1.*((r_load+ro).^2.*(-1.0./2.0)+t15.^2./2.0+t16.^2./2.0+t17.^2./2.0))+dpl1.*(dpl1-k_cbf1.*t15)+dpl2.*(dpl2-k_cbf1.*t16)+dpl3.*(dpl3-k_cbf1.*t17)+t14.*t17.*(t30+gravity.*m+gravity.*mL)+pT1.*t10.*t14.*t15.*t30+pT2.*t10.*t14.*t16.*t30;
end
end
