function [A_qp_cable,b_qp_cable] = CBF_Constraints_cable_angle(obj,in2,in3,U1_val,V4,in6,in7)
%CBF_Constraints_cable_angle
%    [A_qp_cable,B_QP_CABLE] = CBF_Constraints_cable_angle(OBJ,IN2,IN3,U1_val,V4,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/07/29 18:46:04

cableL = in7(:,7);
gamma_c1 = in6(1,:);
gamma_c2 = in6(2,:);
m = in7(:,1);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
A_qp_cable = [0.0,0.0];
if nargout > 1
    t2 = ol1.*pT2;
    t3 = ol2.*pT1;
    t4 = q0.^2;
    t5 = q1.^2;
    t6 = q2.^2;
    t7 = q3.^2;
    t8 = 1.0./cableL;
    t9 = 1.0./m;
    t10 = -t3;
    t11 = -t5;
    t12 = -t6;
    t13 = t4+t7+t11+t12;
    b_qp_cable = -gamma_c1.*(t2+t10)-gamma_c2.*(t2+t10+gamma_c1.*(pT3+9.84807753012208e-1))+ol1.*(ol1.*pT3-ol3.*pT1)+ol2.*(ol2.*pT3-ol3.*pT2)+U1_val.*pT1.*t8.*t9.*(pT1.*t13-pT3.*(q0.*q2.*2.0+q1.*q3.*2.0))+U1_val.*pT2.*t8.*t9.*(pT2.*t13+pT3.*(q0.*q1.*2.0-q2.*q3.*2.0));
end
end
