function [A_load,b_load] = CBF_Constraints_Load(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Load
%    [A_load,B_LOAD] = CBF_Constraints_Load(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/06 15:44:15

c1 = in5(6,:);
c2 = in5(7,:);
cableL = in5(14,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
dstx = in5(15,:);
dsty = in5(16,:);
gravity = in5(12,:);
m = in5(8,:);
mL = in5(13,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in5(1,:);
oy = in5(2,:);
oz = in5(3,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
r_load = in5(5,:);
ro = in5(4,:);
et1 = ((pT1.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT1.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(ox-pl1);
et2 = ((pT2.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT2.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(oy-pl2);
et3 = ((pT3.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(oz-pl3);
A_load = [0.0,0.0,-((m+mL).*(et1+et2+et3))./(pT3.*(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0))];
if nargout > 1
    et4 = ((gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(m+mL).*((pT1.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT1.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)))./pT3;
    et5 = 1.0./(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0);
    et6 = ((gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(m+mL).*((pT2.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT2.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)))./pT3;
    et7 = 1.0./(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0);
    et8 = ((gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)).*(m+mL).*((pT3.*(pT3.*(q0.^2-q1.^2-q2.^2+q3.^2)+pT1.*(q0.*q2.*2.0+q1.*q3.*2.0)-pT2.*(q0.*q1.*2.0-q2.*q3.*2.0)-cableL.*m.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2)))./(m+mL)+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)))./pT3;
    et9 = -1.0./(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0);
    et10 = c2.*(-c1.*((r_load+ro).^2.*(-1.0./2.0)+(ox-pl1).^2./2.0+(oy-pl2).^2./2.0+(oz-pl3).^2./2.0)+dpl1.*(ox-pl1)+dpl2.*(oy-pl2)+dpl3.*(oz-pl3))-dpl1.^2-dpl2.^2-dpl3.^2+(ox-pl1).*(dstx-(cableL.*m.*pT1.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)+et4.*et5);
    et11 = (oy-pl2).*(dsty-(cableL.*m.*pT2.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)+et6.*et7)-(oz-pl3).*(gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./(m+mL)+et8.*et9);
    b_load = et10+et11;
end
end
