function [A_load,b_load] = CBF_Constraints_Load(obj,in2,in3,in4,in5,t)
%CBF_Constraints_Load
%    [A_load,B_LOAD] = CBF_Constraints_Load(OBJ,IN2,IN3,IN4,IN5,T)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2026/06/07 20:02:03

c1 = in5(6,:);
c2 = in5(7,:);
cableL = in5(14,:);
dpl1 = in2(11,:);
dpl2 = in2(12,:);
dpl3 = in2(13,:);
gravity = in5(12,:);
m = in5(8,:);
mL = in5(13,:);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
ox = in5(1,:);
oy = in5(2,:);
oz = in5(3,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
pl1 = in2(8,:);
pl2 = in2(9,:);
pl3 = in2(10,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
r_load = in5(5,:);
ro = in5(4,:);
t2 = m+mL;
t3 = ol1.*pT2;
t4 = ol2.*pT1;
t5 = ol1.*pT3;
t6 = ol3.*pT1;
t7 = ol2.*pT3;
t8 = ol3.*pT2;
t9 = q0.^2;
t10 = q1.^2;
t11 = q2.^2;
t12 = q3.^2;
t13 = q0.*q1.*2.0;
t14 = q0.*q2.*2.0;
t15 = q1.*q3.*2.0;
t16 = q2.*q3.*2.0;
t17 = -pl1;
t18 = -pl2;
t19 = -pl3;
t20 = -t4;
t21 = -t6;
t22 = -t8;
t23 = -t16;
t24 = -t10;
t25 = -t11;
t26 = 1.0./t2;
t27 = ox+t17;
t28 = oy+t18;
t29 = oz+t19;
t36 = t14+t15;
t30 = dpl1.*t27;
t31 = dpl2.*t28;
t32 = dpl3.*t29;
t33 = t3+t20;
t34 = t5+t21;
t35 = t7+t22;
t37 = t13+t23;
t41 = pT1.*t36;
t44 = t9+t12+t24+t25;
t38 = t33.^2;
t39 = t34.^2;
t40 = t35.^2;
t42 = pT2.*t37;
t45 = pT3.*t44;
t43 = -t42;
t46 = t38+t39+t40;
t47 = cableL.*m.*t46;
t48 = -t47;
t49 = pT3.*t26.*t47;
t50 = t41+t43+t45+t48;
A_load = [-t29.*(t49+pT3.*t26.*t50)-t27.*(pT1.*t26.*t47+pT1.*t26.*t50)-t28.*(pT2.*t26.*t47+pT2.*t26.*t50),0.0,0.0];
if nargout > 1
    b_load = -t29.*(gravity+t49)+c2.*(t30+t31+t32-c1.*(abs(t27).^2./2.0+abs(t28).^2./2.0+abs(t29).^2./2.0-(r_load+ro).^2./2.0))+c1.*(t30+t31+t32)-dpl1.^2-dpl2.^2-dpl3.^2+pT1.*t26.*t27.*t48+pT2.*t26.*t28.*t48;
end
end
