function dxf = FLxyzForce(in1,in2)
%FLxyzForce
%    DXF = FLxyzForce(IN1,IN2)
% Input order:
% in1 (state) = ["q0", "q1", "q2", "q3", "o1", "o2", "o3", "pl1", "pl2", "pl3", "dpl1", "dpl2", "dpl3", "pT1", "pT2", "pT3", "ol1", "ol2", "ol3"];
% in2 (parameter) = ["m", "Lx", "Ly", "lx", "ly", "jx", "jy", "jz", "gravity", "km1", "km2", "km3", "km4", "k1", "k2", "k3", "k4", "rotor_r", "mL", "cableL", "Fx", "Fy", "Fz"];



%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026/09/11 13:27:20

Fx = in2(:,21);
Fy = in2(:,22);
Fz = in2(:,23);
cableL = in2(:,20);
dpl1 = in1(11,:);
dpl2 = in1(12,:);
dpl3 = in1(13,:);
gravity = in2(:,9);
jx = in2(:,6);
jy = in2(:,7);
jz = in2(:,8);
m = in2(:,1);
mL = in2(:,19);
o1 = in1(5,:);
o2 = in1(6,:);
o3 = in1(7,:);
ol1 = in1(17,:);
ol2 = in1(18,:);
ol3 = in1(19,:);
pT1 = in1(14,:);
pT2 = in1(15,:);
pT3 = in1(16,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = Fx.*pT1;
t3 = Fy.*pT2;
t4 = Fz.*pT3;
t5 = m+mL;
t6 = ol1.*pT2;
t7 = ol2.*pT1;
t8 = ol1.*pT3;
t9 = ol3.*pT1;
t10 = ol2.*pT3;
t11 = ol3.*pT2;
t12 = 1.0./cableL;
t13 = 1.0./mL;
t14 = -t7;
t15 = -t9;
t16 = -t11;
t17 = 1.0./t5;
t21 = t2+t3+t4;
t18 = t6+t14;
t19 = t8+t15;
t20 = t10+t16;
t22 = t18.^2;
t23 = t19.^2;
t24 = t20.^2;
t25 = t22+t23+t24;
mt1 = [o1.*q1.*(-1.0./2.0)-(o2.*q2)./2.0-(o3.*q3)./2.0;(o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0;(o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0;o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0;(jy.*o2.*o3-jz.*o2.*o3)./jx;-(jx.*o1.*o3-jz.*o1.*o3)./jy;(jx.*o1.*o2-jy.*o1.*o2)./jz;dpl1;dpl2;dpl3;t13.*(Fx-pT1.*t21)+pT1.*t17.*t21-cableL.*m.*pT1.*t17.*t25;t13.*(Fy-pT2.*t21)+pT2.*t17.*t21-cableL.*m.*pT2.*t17.*t25];
mt2 = [-gravity+t13.*(Fz-pT3.*t21)+pT3.*t17.*t21-cableL.*m.*pT3.*t17.*t25;t20;-t8+t9;t18;-t12.*t13.*(Fy.*pT3-Fz.*pT2);t12.*t13.*(Fx.*pT3-Fz.*pT1);-t12.*t13.*(Fx.*pT2-Fy.*pT1)];
dxf = [mt1;mt2];
end
