function dx = SuspendedLoad_RotorLevel_Dynamics(in1, in2, in3)
%SuspendedLoad_RotorLevel_Dynamics  吊り荷付きドローン ロータレベル状態方程式
%    DX = SuspendedLoad_RotorLevel_Dynamics(IN1, IN2, IN3)
%
% with_load_model_mL_euler_for_HL.m と同じ構造だが、入力が各ロータ推力となる。
% 内部でアロケーション行列 B により [T;tau] を計算し、
% 飽和クリッピング後の実効 [T_eff;tau_eff] を状態方程式に適用する。
%
% Input order:
%   in1 (state)     = ["p1","p2","p3","roll","pitch","yaw",
%                       "dp1","dp2","dp3","o1","o2","o3",
%                       "pl1","pl2","pl3","vl1","vl2","vl3",
%                       "pT1","pT2","pT3","ol1","ol2","ol3","mL"];
%   in2 (input)     = ["f1", "f2", "f3", "f4"];  % 各ロータ推力 [N]
%   in3 (parameter) = ["mass", "Lx", "Ly", "lx", "ly", "jx", "jy", "jz", "gravity", "km1", "km2", "km3", "km4", "k1", "k2", "k3", "k4", "rotor_r", "Length", "loadmass", "cableL"];
%
% 2026/09/11  自動生成 by generate_SuspendedLoad_RotorLevel_Dynamics.m

% --- ロータ推力クリッピング (非負 / 最大 5.0 N) ---
f1 = max(0, min(5.0, in2(1,:)));
f2 = max(0, min(5.0, in2(2,:)));
f3 = max(0, min(5.0, in2(3,:)));
f4 = max(0, min(5.0, in2(4,:)));

%SuspendedLoad_RotorLevel_Dynamics_raw
%    DX = SuspendedLoad_RotorLevel_Dynamics_raw(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 12:33:31

Lx = in3(2,:);
Ly = in3(3,:);
cableL = in3(21,:);
dp1 = in1(7,:);
dp2 = in1(8,:);
dp3 = in1(9,:);
f1 = in2(1,:);
f2 = in2(2,:);
f3 = in2(3,:);
f4 = in2(4,:);
gravity = in3(9,:);
jx = in3(6,:);
jy = in3(7,:);
jz = in3(8,:);
km1 = in3(10,:);
km2 = in3(11,:);
km3 = in3(12,:);
km4 = in3(13,:);
lx = in3(4,:);
ly = in3(5,:);
m = in3(1,:);
mL = in1(25,:);
o1 = in1(10,:);
o2 = in1(11,:);
o3 = in1(12,:);
ol1 = in1(22,:);
ol2 = in1(23,:);
ol3 = in1(24,:);
pT1 = in1(19,:);
pT2 = in1(20,:);
pT3 = in1(21,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
vl1 = in1(16,:);
vl2 = in1(17,:);
vl3 = in1(18,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = m+mL;
t10 = ol1.*pT2;
t11 = ol2.*pT1;
t12 = ol1.*pT3;
t13 = ol3.*pT1;
t14 = ol2.*pT3;
t15 = ol3.*pT2;
t16 = 1.0./cableL;
t17 = -gravity;
t18 = 1.0./m;
t24 = f1+f2+f3+f4;
t19 = t3.*t5;
t20 = t5.*t6;
t21 = -t11;
t22 = -t13;
t23 = -t15;
t25 = 1.0./t9;
t26 = t2.*t3.*t7;
t27 = t2.*t6.*t7;
t35 = pT3.*t2.*t4.*t24;
t28 = t10+t21;
t29 = t12+t22;
t30 = t14+t23;
t31 = -t27;
t36 = t20+t26;
t32 = t28.^2;
t33 = t29.^2;
t34 = t30.^2;
t37 = t19+t31;
t38 = pT1.*t24.*t36;
t39 = pT2.*t24.*t37;
t41 = t32+t33+t34;
t40 = -t39;
t42 = cableL.*m.*t41;
t43 = -t42;
t44 = t35+t38+t40+t43;
mt1 = [dp1;dp2;dp3;o1+o3.*t2.*t8+o2.*t5.*t8;o2.*t2-o3.*t5;(o3.*t2+o2.*t5)./t4;t18.*t24.*t36-mL.*pT1.*t18.*t25.*t44;-t18.*t24.*t37-mL.*pT2.*t18.*t25.*t44;t17+t2.*t4.*t18.*t24-mL.*pT3.*t18.*t25.*t44;-(-Ly.*f3-Ly.*f4+f1.*ly+f2.*ly+f3.*ly+f4.*ly-jy.*o2.*o3+jz.*o2.*o3)./jx;(-Lx.*f2-Lx.*f4+f1.*lx+f2.*lx+f3.*lx+f4.*lx-jx.*o1.*o3+jz.*o1.*o3)./jy;(f1.*km1-f2.*km2-f3.*km3+f4.*km4+jx.*o1.*o2-jy.*o1.*o2)./jz;vl1;vl2;vl3;pT1.*t25.*t44;pT2.*t25.*t44];
mt2 = [t17+pT3.*t25.*t44;t30;-t12+t13;t28;-t16.*t18.*t24.*(pT3.*t19+pT3.*t31+pT2.*t2.*t4);-t16.*t18.*t24.*(pT3.*t20+pT3.*t26-pT1.*t2.*t4);pT1.*t16.*t18.*t24.*t37+pT2.*t16.*t18.*t24.*t36;0.0];
dx = [mt1;mt2];
end
