function dx = SuspendedLoad_RotorLevel_Dynamics(in1, in2, in3)
%SuspendedLoad_RotorLevel_Dynamics  吊り荷付きドローンのロータレベル状態方程式
%    DX = SuspendedLoad_RotorLevel_Dynamics(IN1, IN2, IN3)
%
% この関数は generate_SuspendedLoad_RotorLevel_Dynamics.m によって自動生成されました。
% コントローラからの入力 [T; tau] を受け取り、内部でロータ推力に変換・クリッピングし、
% 実効 [T_eff; tau_eff] を用いて状態方程式を計算します。
%
% Input order:
%   in1 (state)     = 25 dimensional state vector
%   in2 (input)     = [T; tau_x; tau_y; tau_z]
%   in3 (parameter) = [mass, Lx, Ly, lx, ly, jx, jy, jz, gravity, km1, km2, km3, km4, ...] (21 dims)

% -----------------------------------------------------------------------
% [T; tau] -> ロータ推力変換 -> クリップ -> 実効 [T_eff; tau_eff]
% -----------------------------------------------------------------------
T_cmd    = in2(1,:);
tau_x    = in2(2,:);
tau_y    = in2(3,:);
tau_z    = in2(4,:);

Lx_s  = in3(:,2);
Ly_s  = in3(:,3);
lx_s  = in3(:,4);
ly_s  = in3(:,5);
km1_s = in3(:,10);
km2_s = in3(:,11);
km3_s = in3(:,12);
km4_s = in3(:,13);

B_mat = [1,    1,         1,       1;
        -ly_s, -ly_s,    (Ly_s-ly_s), (Ly_s-ly_s);
         lx_s, -(Lx_s-lx_s), lx_s, -(Lx_s-lx_s);
         km1_s, -km2_s,  -km3_s,  km4_s];

IIT = inv(B_mat);
f_raw = IIT * [T_cmd; tau_x; tau_y; tau_z];

% 各ロータの最大推力 [N] (非負・最大5.0)
f_clipped = max(0, min(5.0, f_raw));

% 実効入力を再計算
u_eff = B_mat * f_clipped;
u1 = u_eff(1,:);
u2 = u_eff(2,:);
u3 = u_eff(3,:);
u4 = u_eff(4,:);

% -----------------------------------------------------------------------
% シンボリック導出された状態方程式 (u1, u2, u3, u4 を使用)
% -----------------------------------------------------------------------
%SuspendedLoad_RotorLevel_Dynamics_raw
%    DX = SuspendedLoad_RotorLevel_Dynamics_raw(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/11 17:11:13

cableL = in3(:,21);
dp1 = in1(7,:);
dp2 = in1(8,:);
dp3 = in1(9,:);
gravity = in3(:,9);
jx = in3(:,6);
jy = in3(:,7);
jz = in3(:,8);
m = in3(:,1);
mL = in1(25,:);
o1 = in1(10,:);
o2 = in1(11,:);
o3 = in1(12,:);
ol1 = in1(22,:);
ol2 = in1(23,:);
ol3 = in1(24,:);
pT1 = in1(19,:);
pT2 = in1(20,:);
pT3 = in1(21,:);
phi = in1(4,:);
psi = in1(6,:);
theta = in1(5,:);
u1 = u1;
u2 = u2;
u3 = u3;
u4 = u4;
vl1 = in1(16,:);
vl2 = in1(17,:);
vl3 = in1(18,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t8 = tan(theta);
t9 = m+mL;
t10 = ol1.*pT2;
t11 = ol2.*pT1;
t12 = ol1.*pT3;
t13 = ol3.*pT1;
t14 = ol2.*pT3;
t15 = ol3.*pT2;
t16 = 1.0./cableL;
t17 = -gravity;
t18 = 1.0./m;
t19 = t3.*t5;
t20 = t5.*t6;
t21 = -t11;
t22 = -t13;
t23 = -t15;
t24 = 1.0./t9;
t25 = t2.*t3.*t7;
t26 = pT3.*t2.*t4.*u1;
t27 = t2.*t6.*t7;
t28 = t10+t21;
t29 = t12+t22;
t30 = t14+t23;
t32 = -t27;
t36 = t20+t25;
t33 = t28.^2;
t34 = t29.^2;
t35 = t30.^2;
t37 = t19+t32;
t38 = pT1.*t36.*u1;
t40 = pT2.*t37.*u1;
t41 = t33+t34+t35;
t42 = cableL.*m.*t41;
mt1 = [dp1;dp2;dp3;o1+o3.*t2.*t8+o2.*t5.*t8;o2.*t2-o3.*t5;(o3.*t2+o2.*t5)./t4;t18.*t36.*u1-mL.*pT1.*t18.*t24.*(t26+t38-t40-t42);-t18.*t37.*u1-mL.*pT2.*t18.*t24.*(t26+t38-t40-t42);t17+t2.*t4.*t18.*u1-mL.*pT3.*t18.*t24.*(t26+t38-t40-t42);(u2+jy.*o2.*o3-jz.*o2.*o3)./jx;(u3-jx.*o1.*o3+jz.*o1.*o3)./jy;(u4+jx.*o1.*o2-jy.*o1.*o2)./jz;vl1;vl2;vl3;pT1.*t24.*(t26+t38-t40-t42);pT2.*t24.*(t26+t38-t40-t42)];
mt2 = [t17+pT3.*t24.*(t26+t38-t40-t42);t30;-t12+t13;t28;-t16.*t18.*(pT3.*t37.*u1+pT2.*t2.*t4.*u1);-t16.*t18.*(pT3.*t36.*u1-pT1.*t2.*t4.*u1);t16.*t18.*(pT1.*t37.*u1+pT2.*t36.*u1);0.0];
dx = [mt1;mt2];
end

