function dx = three_state_vehicle_model(in1,in2,P)
%THREE_STATE_VEHICLE_MODEL
%    DX = THREE_STATE_VEHICLE_MODEL(IN1,IN2,P)
% Input order:
% in1 (state) = ["", "", "", "", "", "q3"];
% in2 (input) = ["u1", "u6"];
% P (parameter) = [];


%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    19-Jul-2022 23:04:42

q3 = in1(6,:);
u1 = in2(1,:);
u6 = in2(2,:);
dx = [u1.*cos(q3);u1.*sin(q3);0.0;0.0;0.0;u6];
