function cZ1 = Z1_SuspendedLoadxyDst(obj,in2,in3,in4)
%Z1_SuspendedLoadxyDst
%    cZ1 = Z1_SuspendedLoadxyDst(OBJ,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/16 02:19:36

Xd3 = in3(:,3);
dXd3 = in3(:,7);
dpl3 = in2(13,:);
pl3 = in2(10,:);
cZ1 = [-Xd3+pl3;-dXd3+dpl3];
end
