function tra2 = class5_interpolation(t,te,z0,v0,ze,ve)
%CLASS5_INTERPOLATION
%    TRA2 = CLASS5_INTERPOLATION(T,TE,Z0,V0,ZE,VE)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/07/09 10:55:50

t2 = z0.*2.52e+2-ze.*2.52e+2+te.*v0.*1.26e+2+te.*ve.*1.26e+2;
t3 = t2+z0.*2.1e+2-ze.*2.1e+2+te.*v0.*1.26e+2+te.*ve.*8.4e+1;
t4 = t2.*5.0+z0.*1.26e+2-ze.*1.26e+2+te.*v0.*7.0e+1+te.*ve.*5.6e+1;
t5 = t2.*1.0e+1+t3+z0.*9.8e+1-ze.*9.8e+1+te.*v0.*6.3e+1+te.*ve.*3.5e+1;
tra2 = z0+t.*v0-t.^6.*t3.*1.0./te.^6+t.^9.*t5.*1.0./te.^9-t.^10.*t4.*1.0./te.^10+t.^11.*t2.*1.0./te.^11-t.^8.*1.0./te.^8.*(t2.*1.3e+1+z0.*1.89e+2-ze.*1.89e+2+te.*v0.*1.62e+2+te.*ve.*2.7e+1)+t.^7.*1.0./te.^7.*(t2.*7.0+z0.*2.16e+2-ze.*2.16e+2+te.*v0.*1.68e+2+te.*ve.*4.8e+1);
end
