function tra2 = class7_interpolation(t,te,z0,v0,ze,ve)
%CLASS7_INTERPOLATION
%    TRA2 = CLASS7_INTERPOLATION(T,TE,Z0,V0,ZE,VE)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/07/09 10:45:10

t2 = te.^2;
t3 = v0.*4.29e+2;
t4 = ve.*4.29e+2;
t5 = -t4;
t6 = t3+t5;
et1 = z0+(t.^2.*v0)./2.0+(t.^10.*1.0./t2.^4.*(v0.*3.003e+3-ve.*3.003e+3))./3.0e+1+(t.^12.*1.0./t2.^5.*(v0.*6.006e+3-ve.*6.006e+3))./3.3e+1-t.^15.*1.0./te.^13.*(v0.*3.3e+1-ve.*3.3e+1).*(2.0./1.5e+1)-(t.^13.*1.0./te.^11.*(v0.*1.365e+3-ve.*1.365e+3))./1.3e+1-(t.^11.*1.0./te.^9.*(v0.*2.002e+3-ve.*2.002e+3))./1.1e+1-(t.*(z0.*1.287e+4-ze.*1.287e+4+t2.*v0.*4.719e+3+t2.*ve.*1.716e+3))./(te.*1.287e+4);
et2 = (t.^14.*1.0./t2.^6.*t6)./1.3e+1-(t.^9.*t6.*1.0./te.^7)./1.8e+1;
tra2 = et1+et2;
end
