function tra2 = class4_interpolation(t,te,z0,v0,ze,ve)
%CLASS4_INTERPOLATION
%    TRA2 = CLASS4_INTERPOLATION(T,TE,Z0,V0,ZE,VE)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/07/09 10:55:38

t2 = z0.*7.0e+1-ze.*7.0e+1+te.*v0.*3.5e+1+te.*ve.*3.5e+1;
t3 = t2+z0.*5.6e+1-ze.*5.6e+1+te.*v0.*3.5e+1+te.*ve.*2.1e+1;
t4 = t2.*4.0+z0.*3.5e+1-ze.*3.5e+1+te.*v0.*2.0e+1+te.*ve.*1.5e+1;
t5 = t2.*4.0+t3+z0.*1.4e+1-ze.*1.4e+1+te.*v0.*1.4e+1;
tra2 = z0+t.*v0-t.^5.*t3.*1.0./te.^5+t.^6.*t5.*1.0./te.^6+t.^8.*t4.*1.0./te.^8-t.^9.*t2.*1.0./te.^9-t.^7.*1.0./te.^7.*(t2.*3.0+t4+z0.*1.5e+1-ze.*1.5e+1+te.*v0.*1.5e+1);
end
