function tra2 = curve_6order(t,te,z0,v0,ze,ve)
%CURVE_6ORDER
%    TRA2 = CURVE_6ORDER(T,TE,Z0,V0,ZE,VE)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/07/09 10:44:26

t2 = te.^2;
t3 = v0.*2.31e+2;
t4 = ve.*2.31e+2;
t5 = -t4;
t6 = t3+t5;
tra2 = z0+(t.^2.*v0)./2.0-(t.^8.*1.0./t2.^3.*(v0.*3.3e+1-ve.*3.3e+1))./4.0+(t.^13.*1.0./te.^11.*(v0.*4.2e+1-ve.*4.2e+1))./2.6e+1+(t.^11.*1.0./te.^9.*(v0.*3.08e+2-ve.*3.08e+2))./1.1e+1+(t.^9.*1.0./te.^7.*(v0.*3.3e+2-ve.*3.3e+2))./1.2e+1-(t.*(z0.*1.716e+3-ze.*1.716e+3+t2.*t4+t2.*v0.*6.27e+2))./(te.*1.716e+3)-(t.^10.*1.0./t2.^4.*t6)./6.0-(t.^12.*1.0./t2.^5.*t6)./2.2e+1;
end
