function A_att = Attitude_CBF_Acbf(in1,in2)
%Attitude_CBF_Acbf
%    A_att = Attitude_CBF_Acbf(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 23:27:21

jx = in2(:,6);
jy = in2(:,7);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = 1.0./jx;
t7 = 1.0./jy;
t10 = q0.*q1.*2.0i;
t11 = q2.*q3.*2.0i;
t8 = -t3;
t9 = -t4;
t12 = t2+t5+t8+t9;
t13 = t10+t11+t12;
t14 = abs(t13);
t15 = 1.0./t14;
t16 = t7.*t12.*t15;
A_att = reshape([0.0,0.0,0.0,0.0,t6,-t6,0.0,0.0,0.0,0.0,t16,-t16,0.0,0.0,0.0,0.0],[4,4]);
end
