function b_att = Attitude_CBF_bcbf(in1,in2,max_tilt,gamma_att)
%Attitude_CBF_bcbf
%    B_ATT = Attitude_CBF_bcbf(IN1,IN2,MAX_TILT,GAMMA_ATT)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 23:27:21

o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = (imag(min([1.0,q0.*q2.*2.0-q1.*q3.*2.0], [], 2, 'omitnan')) == 0.0);
t3 = (~t2);
t4 = gamma_att.^2;
t5 = q0.^2;
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q0.*q1.*2.0;
t10 = q0.*q2.*2.0;
t11 = q1.*q3.*2.0;
t12 = q2.*q3.*2.0;
t16 = q0.*q1.*2.0i;
t17 = q2.*q3.*2.0i;
t13 = -t11;
t14 = -t6;
t15 = -t7;
t18 = t9+t12;
t19 = t10+t13;
t21 = t5+t8+t14+t15;
t27 = t16+t17+t21;
t28 = abs(t27);
t29 = angle(t27);
t31 = 1.0./t28;
t32 = o3.*t18.*t31;
t33 = o2.*t21.*t31;
t34 = -t33;
t36 = t32+t34;
t37 = gamma_att.*t36.*2.0;
mt1 = [t4.*(max_tilt-t29)-gamma_att.*(o1+o2.*t18.*t31.*1.0./sqrt(-max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan').^2+1.0).*max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')+o3.*t21.*t31.*1.0./sqrt(-max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan').^2+1.0).*max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')).*2.0;t4.*(max_tilt+t29)+gamma_att.*(o1+o2.*t18.*t31.*1.0./sqrt(-max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan').^2+1.0).*max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')+o3.*t21.*t31.*1.0./sqrt(-max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan').^2+1.0).*max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')).*2.0];
mt2 = [t37+t4.*(max_tilt-asin(max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')));-t37+t4.*(max_tilt+asin(max([-1.0,min([1.0,t19], [], 2, 'omitnan')], [], 2, 'omitnan')))];
b_att = [mt1;mt2];
end
