function h_att = Attitude_CBF_h(in1,max_tilt)
%Attitude_CBF_h
%    H_ATT = Attitude_CBF_h(IN1,MAX_TILT)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 17:16:59

q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = (imag(min([1.0,q0.*q2.*2.0-q1.*q3.*2.0], [], 2, 'omitnan')) == 0.0);
t3 = (~t2);
t4 = q0.^2;
t5 = q1.^2;
t6 = q2.^2;
t7 = q3.^2;
t8 = q0.*q2.*2.0;
t9 = q1.*q3.*2.0;
t13 = q0.*q1.*2.0i;
t14 = q2.*q3.*2.0i;
t10 = -t9;
t11 = -t5;
t12 = -t6;
t15 = t8+t10;
t19 = t4+t7+t11+t12+t13+t14;
t20 = angle(t19);
h_att = [max_tilt-t20;max_tilt+t20;max_tilt-asin(max([-1.0,min([1.0,t15], [], 2, 'omitnan')], [], 2, 'omitnan'));max_tilt+asin(max([-1.0,min([1.0,t15], [], 2, 'omitnan')], [], 2, 'omitnan'))];
end
