function Lg = C3BF_Lg(in1,in2,in3)
%C3BF_Lg
%    Lg = C3BF_Lg(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 15:10:47

dp1 = in1(8,:);
dp2 = in1(9,:);
dp3 = in1(10,:);
m = in3(:,1);
p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
px_obs = in2(:,1);
py_obs = in2(:,2);
pz_obs = in2(:,3);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
robs = in2(:,7);
vx_obs = in2(:,4);
vy_obs = in2(:,5);
vz_obs = in2(:,6);
t2 = robs.^2;
t3 = 1.0./m;
t4 = -px_obs;
t5 = -py_obs;
t6 = -pz_obs;
t7 = -vx_obs;
t8 = -vy_obs;
t9 = -vz_obs;
t10 = -t2;
t11 = dp1+t7;
t12 = dp2+t8;
t13 = dp3+t9;
t14 = p1+t4;
t15 = p2+t5;
t16 = p3+t6;
t17 = t11.^2;
t18 = t12.^2;
t19 = t13.^2;
t20 = t14.^2;
t21 = t15.^2;
t22 = t16.^2;
t23 = t10+t20+t21+t22;
t24 = t17+t18+t19+1.0e-6;
t25 = sqrt(t23);
t27 = 1.0./sqrt(t24);
t26 = conj(t25);
Lg = [t3.*(t16+(t26.*t27.*(dp3.*2.0-vz_obs.*2.0))./2.0).*(q0.^2-q1.^2-q2.^2+q3.^2)+t3.*(t14+(t26.*t27.*(dp1.*2.0-vx_obs.*2.0))./2.0).*(q0.*q2.*2.0+q1.*q3.*2.0)-t3.*(t15+(t26.*t27.*(dp2.*2.0-vy_obs.*2.0))./2.0).*(q0.*q1.*2.0-q2.*q3.*2.0),0.0,0.0,0.0];
end
