function Lf = C3BF_Lf(in1,in2,in3)
%C3BF_Lf
%    Lf = C3BF_Lf(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 15:10:47

dp1 = in1(8,:);
dp2 = in1(9,:);
dp3 = in1(10,:);
gravity = in3(:,9);
p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
px_obs = in2(:,1);
py_obs = in2(:,2);
pz_obs = in2(:,3);
robs = in2(:,7);
vx_obs = in2(:,4);
vy_obs = in2(:,5);
vz_obs = in2(:,6);
t2 = robs.^2;
t3 = -px_obs;
t4 = -py_obs;
t5 = -pz_obs;
t6 = -vx_obs;
t7 = -vy_obs;
t8 = -vz_obs;
t9 = -t2;
t10 = dp1+t6;
t11 = dp2+t7;
t12 = dp3+t8;
t13 = p1+t3;
t14 = p2+t4;
t15 = p3+t5;
t16 = t10.^2;
t17 = t11.^2;
t18 = t12.^2;
t19 = t13.^2;
t20 = t14.^2;
t21 = t15.^2;
t22 = t9+t19+t20+t21;
t23 = t16+t17+t18+1.0e-6;
t24 = sqrt(t22);
t26 = sqrt(t23);
t25 = conj(t24);
t27 = 1.0./t25;
Lf = -gravity.*(t15+(t25.*(dp3.*2.0-vz_obs.*2.0))./(t26.*2.0))+dp1.*(t10+(t26.*t27.*(p1.*2.0-px_obs.*2.0))./2.0)+dp2.*(t11+(t26.*t27.*(p2.*2.0-py_obs.*2.0))./2.0)+dp3.*(t12+(t26.*t27.*(p3.*2.0-pz_obs.*2.0))./2.0);
end
