function [A_f,b_cbf,h,h_dot] = CBF_Constraints_MRD_Core(in1,in2,in3,in4,in5,ro,r_l,lambda,m,mL,L,g,k1,k2)
%CBF_Constraints_MRD_Core
%    [A_f,B_CBF,H,H_DOT] = CBF_Constraints_MRD_Core(IN1,IN2,IN3,IN4,IN5,RO,R_L,LAMBDA,M,mL,L,G,K1,K2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/04 15:52:55

pL1 = in1(1,:);
pL2 = in1(2,:);
pL3 = in1(3,:);
pT1 = in3(1,:);
pT2 = in3(2,:);
pT3 = in3(3,:);
vL1 = in2(1,:);
vL2 = in2(2,:);
vL3 = in2(3,:);
wL1 = in4(1,:);
wL2 = in4(2,:);
wL3 = in4(3,:);
xo = in5(1,:);
yo = in5(2,:);
zo = in5(3,:);
t2 = m+mL;
t3 = r_l+ro;
t4 = pT1.*wL2;
t5 = pT2.*wL1;
t6 = pT1.*wL3;
t7 = pT3.*wL1;
t8 = pT2.*wL3;
t9 = pT3.*wL2;
t10 = pL1.*2.0;
t11 = pL2.*2.0;
t12 = pL3.*2.0;
t13 = pT1.^2;
t14 = pT2.^2;
t15 = pT3.^2;
t16 = xo.*2.0;
t17 = yo.*2.0;
t18 = zo.*2.0;
t19 = L.*lambda.*pT1;
t20 = L.*lambda.*pT2;
t21 = L.*lambda.*pT3;
t22 = 1.0./m;
t23 = -pL1;
t25 = -pL2;
t27 = -pL3;
t24 = -t10;
t26 = -t11;
t28 = -t12;
t29 = -t5;
t30 = -t7;
t31 = -t9;
t32 = t19.*2.0;
t33 = t20.*2.0;
t34 = t21.*2.0;
t35 = t3.^2;
t36 = 1.0./t2;
t38 = lambda.*pT1.*pT2.*t22;
t39 = lambda.*pT1.*pT3.*t22;
t40 = lambda.*pT2.*pT3.*t22;
t47 = t19+t23+xo;
t48 = t20+t25+yo;
t49 = t21+t27+zo;
t37 = -t35;
t41 = pT1.*pT2.*t36;
t42 = pT1.*pT3.*t36;
t43 = pT2.*pT3.*t36;
t44 = t4+t29;
t45 = t6+t30;
t46 = t8+t31;
t59 = t47.^2;
t60 = t48.^2;
t61 = t49.^2;
t62 = t16+t24+t32;
t63 = t17+t26+t33;
t64 = t18+t28+t34;
A_f = [-t62.*(t13.*t36+lambda.*(t22-t13.*t22))+t63.*(t38-t41)+t64.*(t39-t42),-t63.*(t14.*t36+lambda.*(t22-t14.*t22))+t62.*(t38-t41)+t64.*(t40-t43),-t64.*(t15.*t36+lambda.*(t22-t15.*t22))+t62.*(t39-t42)+t63.*(t40-t43)];
if nargout > 1
    t53 = t44.^2;
    t54 = t45.^2;
    t55 = t46.^2;
    t56 = L.*lambda.*t44;
    t57 = L.*lambda.*t45;
    t58 = L.*lambda.*t46;
    t76 = t37+t59+t60+t61;
    t66 = t56+vL3;
    t67 = t58+vL1;
    t74 = -t63.*(t57-vL2);
    t75 = t53+t54+t55;
    t72 = t62.*t67;
    t73 = t64.*t66;
    b_cbf = (t57-vL2).^2.*-2.0-k2.*t76-t64.*(g-t21.*t75+L.*m.*pT3.*t36.*t75)+k1.*(t72+t73+t74)-t66.^2.*2.0-t67.^2.*2.0+t62.*(t19.*t75-L.*m.*pT1.*t36.*t75)+t63.*(t20.*t75-L.*m.*pT2.*t36.*t75);
end
if nargout > 2
    h = t76;
end
if nargout > 3
    h_dot = -t72-t73+t63.*(t57-vL2);
end
end
