function h_val = CBF_h_cc(in1,in2)
%CBF_h_cc
%    H_VAL = CBF_h_cc(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/30 00:54:33

A11 = in2(4,:);
A12 = in2(5,:);
A13 = in2(6,:);
A22 = in2(7,:);
A23 = in2(8,:);
A33 = in2(9,:);
c_scale = in2(10,:);
dp1 = in1(8,:);
dp2 = in1(9,:);
dp3 = in1(10,:);
mu1 = in2(1,:);
mu2 = in2(2,:);
mu3 = in2(3,:);
p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
t2 = -p1;
t3 = -p2;
t4 = -p3;
t5 = mu1+t2;
t6 = mu2+t3;
t7 = mu3+t4;
t8 = A11.*t5;
t9 = A12.*t5;
t10 = A13.*t5;
t11 = A12.*t6;
t12 = A13.*t7;
t13 = A22.*t6;
t14 = A23.*t6;
t15 = A23.*t7;
t16 = A33.*t7;
t17 = t8+t11+t12;
t18 = t9+t13+t15;
t19 = t10+t14+t16;
h_val = -(dp1.*t17+dp2.*t18+dp3.*t19).^2+(dp1.*(A11.*dp1+A12.*dp2+A13.*dp3)+dp2.*(A12.*dp1+A22.*dp2+A23.*dp3)+dp3.*(A13.*dp1+A23.*dp2+A33.*dp3)).*(t5.*t17+t6.*t18+t7.*t19-c_scale.^2);
end
