function h = ECBF_h(in1,in2,in3)
%ECBF_h
%    H = ECBF_h(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 23:27:20

dp1 = in1(8,:);
dp2 = in1(9,:);
dp3 = in1(10,:);
p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
px_obs = in2(:,1);
py_obs = in2(:,2);
pz_obs = in2(:,3);
robs = in2(:,7);
vx_obs = in2(:,4);
vy_obs = in2(:,5);
vz_obs = in2(:,6);
t2 = -px_obs;
t3 = -py_obs;
t4 = -pz_obs;
t5 = -vx_obs;
t6 = -vy_obs;
t7 = -vz_obs;
t8 = dp1+t5;
t9 = dp2+t6;
t10 = dp3+t7;
t11 = p1+t2;
t12 = p2+t3;
t13 = p3+t4;
h = sqrt(-robs.^2+t11.^2+t12.^2+t13.^2).*sqrt(t8.^2+t9.^2+t10.^2+1.0e-8)+t8.*t11+t9.*t12+t10.*t13;
end
