function h = Pos_ECBF_h(in1,in2,in3)
%Pos_ECBF_h
%    H = Pos_ECBF_h(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 23:03:12

p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
px_obs = in2(:,1);
py_obs = in2(:,2);
pz_obs = in2(:,3);
rdrone = in2(:,8);
robs = in2(:,7);
h = -(rdrone+robs).^2+(p1-px_obs).^2+(p2-py_obs).^2+(p3-pz_obs).^2;
end
