function A_cbf = Pos_ECBF_Acbf(in1,in2,in3,f_T_curr)
%Pos_ECBF_Acbf
%    A_cbf = Pos_ECBF_Acbf(IN1,IN2,IN3,f_T_curr)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/08/29 23:03:12

jx = in3(:,6);
jy = in3(:,7);
m = in3(:,1);
p1 = in1(5,:);
p2 = in1(6,:);
p3 = in1(7,:);
px_obs = in2(:,1);
py_obs = in2(:,2);
pz_obs = in2(:,3);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = p1.*2.0;
t3 = p2.*2.0;
t4 = p3.*2.0;
t5 = px_obs.*2.0;
t6 = py_obs.*2.0;
t7 = pz_obs.*2.0;
t8 = q0.^2;
t9 = q1.^2;
t10 = q2.^2;
t11 = q3.^2;
t12 = q0.*q1.*2.0;
t13 = q0.*q2.*2.0;
t14 = q0.*q3.*2.0;
t15 = q1.*q2.*2.0;
t16 = q1.*q3.*2.0;
t17 = q2.*q3.*2.0;
t18 = 1.0./jx;
t19 = 1.0./jy;
t20 = 1.0./m;
t21 = -t5;
t22 = -t6;
t23 = -t7;
t24 = -t15;
t25 = -t16;
t26 = -t17;
t27 = -t8;
t28 = -t9;
t29 = -t10;
t30 = -t11;
t34 = t12+t17;
t35 = t13+t16;
t36 = t14+t15;
t31 = t2+t21;
t32 = t3+t22;
t33 = t4+t23;
t37 = t12+t26;
t38 = t13+t25;
t39 = t14+t24;
t40 = t9+t10+t11+t27;
t41 = t8+t10+t28+t30;
t42 = t8+t9+t29+t30;
A_cbf = [-t20.*t31.*t35+t20.*t32.*t37+t20.*t33.*t40,t18.*t31.*(f_T_curr.*t20.*t37.*t38+f_T_curr.*t20.*t36.*t40)+t18.*t33.*(f_T_curr.*t20.*t35.*t36+f_T_curr.*t20.*t37.*t42)+t18.*t32.*(f_T_curr.*t20.*t35.*t38-f_T_curr.*t20.*t40.*t42),-t19.*t32.*(f_T_curr.*t20.*t34.*t35-f_T_curr.*t20.*t39.*t40)-t19.*t31.*(f_T_curr.*t20.*t34.*t37-f_T_curr.*t20.*t40.*t41)+t19.*t33.*(f_T_curr.*t20.*t35.*t41-f_T_curr.*t20.*t37.*t39),0.0];
end
