function [A_cbf,b_cbf,h,dh,ddh,dddh] = Sphere_Snap_CBF(in1,in2,in3)
%Sphere_Snap_CBF
%    [A_cbf,B_CBF,H,DH,DDH,DDDH] = Sphere_Snap_CBF(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 26.1.
%    2026/09/05 12:35:56

a1 = in1(7,:);
a2 = in1(8,:);
a3 = in1(9,:);
j1 = in1(10,:);
j2 = in1(11,:);
j3 = in1(12,:);
k0 = in3(1,:);
k1 = in3(2,:);
k2 = in3(3,:);
k3 = in3(4,:);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
p_obs1 = in2(1,:);
p_obs2 = in2(2,:);
p_obs3 = in2(3,:);
r_obs = in2(4,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
t2 = p1.*2.0;
t3 = p2.*2.0;
t4 = p3.*2.0;
t5 = p_obs1.*2.0;
t6 = p_obs2.*2.0;
t7 = p_obs3.*2.0;
A_cbf = [-t2+t5,-t3+t6,-t4+t7];
if nargout > 1
    t8 = r_obs.^2;
    t9 = v1.^2;
    t10 = v2.^2;
    t11 = v3.^2;
    t12 = a1.*v1.*6.0;
    t13 = a2.*v2.*6.0;
    t14 = a3.*v3.*6.0;
    t15 = -p_obs1;
    t17 = -p_obs2;
    t19 = -p_obs3;
    t16 = -t5;
    t18 = -t6;
    t20 = -t7;
    t21 = t9.*2.0;
    t22 = t10.*2.0;
    t23 = t11.*2.0;
    t24 = -t8;
    t25 = p1+t15;
    t26 = p2+t17;
    t27 = p3+t19;
    t28 = t2+t16;
    t29 = t3+t18;
    t30 = t4+t20;
    t31 = t25.^2;
    t32 = t26.^2;
    t33 = t27.^2;
    t34 = a1.*t28;
    t35 = a2.*t29;
    t36 = a3.*t30;
    t37 = j1.*t28;
    t38 = j2.*t29;
    t39 = j3.*t30;
    t40 = t28.*v1;
    t41 = t29.*v2;
    t42 = t30.*v3;
    t43 = t24+t31+t32+t33;
    t44 = t40+t41+t42;
    t45 = t12+t13+t14+t37+t38+t39;
    t46 = t21+t22+t23+t34+t35+t36;
    b_cbf = k0.*t43+k1.*t44+k2.*t46+k3.*t45+j1.*v1.*8.0+j2.*v2.*8.0+j3.*v3.*8.0+a1.^2.*6.0+a2.^2.*6.0+a3.^2.*6.0;
end
if nargout > 2
    h = t43;
end
if nargout > 3
    dh = t44;
end
if nargout > 4
    ddh = t46;
end
if nargout > 5
    dddh = t45;
end
end
