function U1 = thrust_force_Uf(in1,in2,in3,in4)
%thrust_force_Uf
%    U1 = thrust_force_Uf(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/17 19:39:36

Lx = in4(:,2);
Ly = in4(:,3);
V1 = in3(:,1);
ddXd3 = in2(:,11);
gravity = in4(:,9);
km1 = in4(:,10);
km2 = in4(:,11);
km3 = in4(:,12);
km4 = in4(:,13);
lx = in4(:,4);
ly = in4(:,5);
m = in4(:,1);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = Lx.*Ly.*km1;
t7 = Lx.*Ly.*km2;
t8 = Lx.*Ly.*km3;
t9 = Lx.*Ly.*km4;
t10 = V1+ddXd3+gravity;
t11 = Lx.*km1.*ly;
t12 = Ly.*km1.*lx;
t13 = Lx.*km2.*ly;
t14 = Ly.*km2.*lx;
t15 = Lx.*km3.*ly;
t16 = Ly.*km3.*lx;
t17 = Lx.*km4.*ly;
t18 = Ly.*km4.*lx;
t19 = -t3;
t20 = -t4;
t21 = t6+t7+t8+t9;
t22 = t2+t5+t19+t20;
t23 = 1.0./t21;
t24 = 1.0./t22;
U1 = [-m.*t10.*t23.*t24.*(-t7-t8-t9+t13+t16+t17+t18);m.*t10.*t23.*t24.*(t6-t11-t15+t16+t18);m.*t10.*t23.*t24.*(t6-t12+t13-t14+t17);m.*t10.*t23.*t24.*(-t6+t11+t12+t14+t15)];
end
