function cZ3 = thrust_force_Z3(in1,in2,in3,in4)
%thrust_force_Z3
%    cZ3 = thrust_force_Z3(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/17 19:39:35

V1 = in3(:,1);
Xd2 = in2(:,2);
dV1 = in3(:,2);
dXd2 = in2(:,6);
ddXd2 = in2(:,10);
ddXd3 = in2(:,11);
dddXd2 = in2(:,14);
dddXd3 = in2(:,15);
dp2 = in1(9,:);
gravity = in4(:,9);
m = in4(:,1);
o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
p2 = in1(6,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = V1.*m;
t3 = ddXd3.*m;
t4 = gravity.*m;
t5 = q0.*q1;
t6 = q2.*q3;
t7 = q0.^2;
t8 = q1.^2;
t9 = q2.^2;
t10 = q3.^2;
t11 = 1.0./m;
t12 = -t6;
t13 = -t8;
t14 = -t9;
t16 = t2+t3+t4;
t15 = t5+t12;
t17 = t7+t10+t13+t14;
t18 = 1.0./t17;
t19 = t18.^2;
cZ3 = [-Xd2+p2;-dXd2+dp2;-ddXd2-t11.*t15.*t16.*t18.*2.0;-dddXd2-(q0.*t11.*t16.*t18.*2.0+q1.*t11.*t15.*t16.*t19.*4.0).*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0)+(q1.*t11.*t16.*t18.*2.0-q0.*t11.*t15.*t16.*t19.*4.0).*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0)+(q2.*t11.*t16.*t18.*2.0+q3.*t11.*t15.*t16.*t19.*4.0).*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0)+(q3.*t11.*t16.*t18.*2.0-q2.*t11.*t15.*t16.*t19.*4.0).*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0)-t11.*t15.*t18.*(dV1.*m+dddXd3.*m).*2.0];
end
