function cZ2 = thrust_force_Z2(in1,in2,in3,in4)
%thrust_force_Z2
%    cZ2 = thrust_force_Z2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2025/10/17 19:39:35

V1 = in3(:,1);
Xd1 = in2(:,1);
dV1 = in3(:,2);
dXd1 = in2(:,5);
ddXd1 = in2(:,9);
ddXd3 = in2(:,11);
dddXd1 = in2(:,13);
dddXd3 = in2(:,15);
dp1 = in1(8,:);
gravity = in4(:,9);
m = in4(:,1);
o1 = in1(11,:);
o2 = in1(12,:);
o3 = in1(13,:);
p1 = in1(5,:);
q0 = in1(1,:);
q1 = in1(2,:);
q2 = in1(3,:);
q3 = in1(4,:);
t2 = V1.*m;
t3 = ddXd3.*m;
t4 = gravity.*m;
t5 = q0.*q2;
t6 = q1.*q3;
t7 = q0.^2;
t8 = q1.^2;
t9 = q2.^2;
t10 = q3.^2;
t11 = 1.0./m;
t12 = -t8;
t13 = -t9;
t14 = t5+t6;
t15 = t2+t3+t4;
t16 = t7+t10+t12+t13;
t17 = 1.0./t16;
t18 = t17.^2;
cZ2 = [-Xd1+p1;-dXd1+dp1;-ddXd1+t11.*t14.*t15.*t17.*2.0;-dddXd1+(q0.*t11.*t15.*t17.*2.0+q2.*t11.*t14.*t15.*t18.*4.0).*((o2.*q0)./2.0+(o1.*q3)./2.0-(o3.*q1)./2.0)+(q1.*t11.*t15.*t17.*2.0-q3.*t11.*t14.*t15.*t18.*4.0).*(o1.*q2.*(-1.0./2.0)+(o2.*q1)./2.0+(o3.*q0)./2.0)-(q2.*t11.*t15.*t17.*2.0-q0.*t11.*t14.*t15.*t18.*4.0).*((o1.*q1)./2.0+(o2.*q2)./2.0+(o3.*q3)./2.0)+(q3.*t11.*t15.*t17.*2.0+q1.*t11.*t14.*t15.*t18.*4.0).*((o1.*q0)./2.0-(o2.*q3)./2.0+(o3.*q2)./2.0)+t11.*t14.*t17.*(dV1.*m+dddXd3.*m).*2.0];
end
