function H234 = H234_SuspendedLoadxyDst(obj,in2,in3,in4,in5)
%H234_SuspendedLoadxyDst
%    H234 = H234_SuspendedLoadxyDst(OBJ,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026/09/11 14:26:57

H234 = reshape([0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,3]);
end
