function [A_v,b_v] = Get_ECBF_LinearSpace_Constraint(in1,in2,in3)
%Get_ECBF_LinearSpace_Constraint
%    [A_v,B_V] = Get_ECBF_LinearSpace_Constraint(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026/05/25 13:17:27

R_safe = in3(:,3);
ax_L = in2(1,:);
ay_L = in2(2,:);
dpl1 = in1(11,:);
dpl2 = in1(12,:);
jx_L = in2(3,:);
jy_L = in2(4,:);
k0_cbf = in3(:,4);
k1_cbf = in3(:,5);
k2_cbf = in3(:,6);
k3_cbf = in3(:,7);
ox = in3(:,1);
oy = in3(:,2);
pl1 = in1(8,:);
pl2 = in1(9,:);
t2 = ox.*2.0;
t3 = oy.*2.0;
t4 = pl1.*2.0;
t5 = pl2.*2.0;
A_v = [-t2+t4,-t3+t5];
if nargout > 1
    t6 = -t4;
    t7 = -t5;
    t8 = t2+t6;
    t9 = t3+t7;
    b_v = dpl1.*jx_L.*-8.0-dpl2.*jy_L.*8.0-k0_cbf.*(-R_safe.^2+(ox-pl1).^2+(oy-pl2).^2)+k1_cbf.*(dpl1.*t8+dpl2.*t9)-ax_L.^2.*6.0-ay_L.^2.*6.0+k2_cbf.*(ax_L.*t8+ay_L.*t9-dpl1.^2.*2.0-dpl2.^2.*2.0)-k3_cbf.*(ax_L.*dpl1.*6.0+ay_L.*dpl2.*6.0-jx_L.*t8-jy_L.*t9);
end
end
