function U1 = Uf_SuspendedLoadxyDst(obj,in2,in3,in4,in5)
%Uf_SuspendedLoadxyDst
%    U1 = Uf_SuspendedLoadxyDst(OBJ,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025/03/15 02:01:15

V1 = in4(:,1);
cableL = in5(:,7);
d2Xd3 = in3(:,11);
gravity = in5(:,5);
m = in5(:,1);
mL = in5(:,6);
ol1 = in2(17,:);
ol2 = in2(18,:);
ol3 = in2(19,:);
pT1 = in2(14,:);
pT2 = in2(15,:);
pT3 = in2(16,:);
q0 = in2(1,:);
q1 = in2(2,:);
q2 = in2(3,:);
q3 = in2(4,:);
t2 = m+mL;
U1 = [(t2.*(V1+d2Xd3+gravity+(cableL.*m.*pT3.*((ol1.*pT2-ol2.*pT1).^2+(ol1.*pT3-ol3.*pT1).^2+(ol2.*pT3-ol3.*pT2).^2))./t2))./(pT3.*(pT3.*q0.^2-pT3.*q1.^2-pT3.*q2.^2+pT3.*q3.^2+pT1.*q0.*q2.*2.0-pT2.*q0.*q1.*2.0+pT1.*q1.*q3.*2.0+pT2.*q2.*q3.*2.0));0.0;0.0;0.0];
end
